<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>PhysicsSmokeTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../GameCore/GameCore.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug' Or '$(Configuration)' == 'ExportDebug'">
    <PackageReference Include="FFS.StaticPack.Debug" Version="1.2.6" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release' Or '$(Configuration)' == 'ExportRelease'">
    <PackageReference Include="FFS.StaticPack" Version="1.2.6" />
  </ItemGroup>
</Project>
